name: Deploy to Neocities

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Neocities
        uses: crowlKats/deploy-to-neocities@v1.0
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          dist_dir: .
          exclude: ".git,.github,node_modules,deploy.js,package.json,package-lock.json"
