name: Deploy to Neocities

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload to Neocities
        run: |
          find ./_site -type f \
          | while read file; do
            curl -s \
              -F "${file#./_site/}=@${file}" \
              "https://neocities.org/api/upload" \
              -H "Authorization: Bearer ${{ secrets.NEOCITIES_API_TOKEN }}"
          done
